name: CI
on: [push, pull_request]
jobs:
  check:
    name: Check with Node.js v${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['18']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: 📦 Install dependencies
        run: pnpm install
      - name: ESLint check
        run: pnpm lint
